User:
  name: Aquiles

Params:
  resistance: 100ohm
  port: COM5 #COM3, COM4
  device_type: dummy #(or real)

Scan:
  start: 0V
  stop: 3300mV
  step: 100mV
  delay: 50ms
  channel_in: 0
  channel_out: 0

Saving:
  filename: IV_data
  path: C:\\Users\\Simone\\LMU_04_19\\data